# Real Estate Clean up

This is a real dataset, and it was downloaded using web scraping techniques. The data contains registers from **Fotocasa** which is one of the most popular real estate websites in Spain. Please, do not do this (web scraping) unless it is for academic purposes.

The dataset was downloaded a few years ago by Henry Navarro, and in no case were economic returns obtained from it.

It contains thousands of data from real houses published on the web www.fotocasa.com. Your goal is to extract as much information as possible with the knowledge you have so far about data science, for example what is the most expensive house in the entire dataset?

Let's start with precisely that question... Good luck!

#### Exercise 00. Read the dataset assets/real_estate.csv and try to visualize the table (★☆☆)

In [1]:
import pandas as pd

# This CSV file contains semicolons instead of comas as separator
ds = pd.read_csv('assets/real_estate.csv', sep=';')
ds

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,15331,153901377,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,96.0,259470,...,0,0,0,0,0,0,"40,45416","-3,70286",NaN,NaN
15331,15332,150394373,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,150.0,165000,...,0,0,0,0,0,0,"40,36652","-3,48951",NaN,NaN
15332,15333,153901397,False,tecnocasa torrelodones,912780348.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,175.0,495000,...,0,0,0,0,0,0,"40,57444","-3,92124",NaN,NaN
15333,15334,152607440,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,101.0,195000,...,0,0,0,0,0,0,"40,36967","-3,48105",NaN,NaN
15334,15335,153901356,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,152.0,765000,...,0,0,0,0,0,0,"40,45773","-3,69068",NaN,NaN

#### Exercise 01. Which is the most expensive house in the dataset? (★☆☆)

Print the address and the price of the selected house. For example:

`The house with address General Street Nº5 is the most expensive and its price is 5000000 USD`

In [ ]:
# TODO
#Cálculo de la casa mas cara
casa_mas_cara = ds.price.max()

#Cálculo de indice y de direccion de la casa
dirección_cmc = ds.address[ds[ds['price'] == casa_mas_cara].index[0]]

#Impresión de dato solicitado
print(f"La casa con dirección en {dirección_cmc} es la más cara y su precio es de {casa_mas_cara} €")

#### Exercise 02. Which is the cheapest house in the dataset? (★☆☆)

Print the address and the price of the selected house. For example:

`The house with address Concrete Street Nº1 is the cheapest and its price is 12000 USD`

In [ ]:
# TODO
#Cálculo de la casa más barata filtrando del dataset los precios diferentes de cero
casa_mas_barata = ds[ds['price'] != 0]['price'].min()

#Cálculo de indice y dirección de la casa
dirección_cmb = ds.address[ds[(ds['price'] != 0) & (ds['price'] == casa_mas_barata)].index[0]]

#Impresión de dato solicitado
print(f"La casa con dirección en {dirección_cmb} es la más económica y su precio es de {casa_mas_barata} €")

#### Exercise 03. Which is the biggest and the smallest house in the dataset? (★☆☆)

Print both the address and the surface of the selected houses. For example:

`The biggest house is located on Yukka Street Nº10 and its surface is 5000 meters`

`The smallest house is located on County Road 1 N and its surface is 200 meters`

In [ ]:
# TODO
#Calculo de casa más grande
casa_mas_grande = ds.surface.max()

#Calculo de indice y dirección de la casa
dirección_cmg = ds.address[ds.surface.idxmax()]

#Impresión del dato solicitado
print(f"La casa mas grande está ubicada en {dirección_cmg} y su superficie es de {casa_mas_grande} metros")

#Calculo de casa más pequeña
casa_mas_pequeña = ds.surface.min()

#Calculo de indice y dirección de la casa
dirección_cmp = ds.address[ds.surface.idxmin()]

#Impresión del dato solicitado
print(f"La casa mas pequeña está ubicada en {dirección_cmp} y su superficie es de {casa_mas_pequeña} metros")

#### Exercise 04. How many populations (level5 column) the dataset contains? (★☆☆)

Print the names of the populations with a comma as a separator. For example:

`> print(populations)`

`population1, population2, population3, ...`

In [ ]:
# TODO
#Cálculo de cuantos datos únicos están en la columna indicada
poblaciones = len(ds.level5.unique())

#Impresión de cantidad de poblaciones en el dataset y datos en la columna
print(f"Hay {poblaciones} poblaciones en el dataset:")
print(ds.level5.unique() + ",")

#### Exercise 05. Does the dataset contain NAs? (★☆☆)

Print a boolean value (`True` or `False`) followed by the rows/cols that contains NAs.

In [ ]:
# TODO
#Impresión de información solicitada
print(ds.isnull())

#### Exercise 06. Delete the NAs of the dataset, if applicable (★★☆)

Print a comparison between the dimensions of the original DataFrame versus the DataFrame after the deletions.

In [ ]:
# TODO
#Impresión de total de valores nulos
print("Resumen de Valores Nulos:")
print(ds.isnull().sum())

#Eliminación de columnas con valores nulos
ds1 = ds.drop(columns = ['level4', 'level6', 'level7', 'level8'])
ds1 = ds1.loc[:, (ds1.notna().any()) & ((ds1 != 0).any())]

#Eliminación de valores cero en columnas de superficie y precio
ds1 = ds1[(ds1['surface'] > 0) & (ds1['price'] != 0)]

#Columnas del dataset eliminadas
columnas_eliminadas = set(ds.columns) - set(ds1.columns)

#Impresión de comparativa de datasets y columnas eliminadas
print(f'\nColumnas eliminadas: {columnas_eliminadas}')
print(f'\nAntes de limpiar datos: {ds.shape}')
print(f'Después de limpiar datos: {ds1.shape}')

#### Exercise 07. Which is the mean of prices in the population (level5 column) of "Arroyomolinos (Madrid)"? (★★☆)

Print the obtained value.

In [ ]:
# TODO
#Importar biblioteca adicionales
import numpy as np

#Cálculo de dato solicitado
media = ds1.price[ds1.level5 == 'Arroyomolinos (Madrid)'].mean()

#Impresión de dato solicitado
print(f"La media de precios en la popblación de 'Arroyomolinos (Madrid)' es: {media:.2f} €")

#### Exercise 08. Plot the histogram of prices for the population (level5 column) of "Arroyomolinos (Madrid)" and explain what you observe (★★☆)

Print the histogram of the prices and write in the Markdown cell a brief analysis about the plot.

In [ ]:
# TODO: Code
#Importar bibliotecas adicionales
import matplotlib.pyplot as plt
%matplotlib inline

#calcular datos a graficar y realizar gráfico
Arroyo = ds1[ds1.level5 == 'Arroyomolinos (Madrid)']
Arroyo['price'].plot(kind = 'hist', alpha = 0.6, legend = True)

#Configurar Etiquetas y Título
plt.xlabel('Precio')
plt.ylabel('Frecuencia')
plt.title('Histograma de Precio para Arroyomolinos (Madrid)')
plt.grid(True)

#Mostrar el gráfico
plt.show()

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 09. Are the average prices of "Valdemorillo" and "Galapagar" the same? (★★☆)

Print both average prices and then write a conclusion about them.

In [ ]:
# TODO
#Cálculo de precio promedio en la población de Valdemorillo
mediaValdemorillo = ds1.price[ds1.level5 == 'Valdemorillo'].mean()

#Impresión del precio promedio de Valdemorillo
print(f"La media de precios en la población de 'Valdemorillo' es: {mediaValdemorillo:.2f} euros")

#Cálculo de precio promedio en la población de Galapagar
mediaGalapagar = ds1.price[ds1.level5 == 'Galapagar'].mean()

#Impresión del precio promedio de Galapagar
print(f"La media de precios en la población de 'Galapagar' es: {mediaGalapagar:.2f} euros")

#### Exercise 10. Are the average prices per square meter (price/m2) of "Valdemorillo" and "Galapagar" the same? (★★☆)

Print both average prices and then write a conclusion about it.

Hint: Create a new column called `pps` (price per square meter) and then analyze the values.

In [ ]:
# TODO
#Cálculo de precio por metro cuadrado (pps) para añadir como columna nueva al dataset
ds1['pps'] = ds1['price'] / ds1['surface']

#Cálculo e Impresión del promedio pps de la poblacion de 'Valdemorillo'
ppsv = ds1.pps[ds1.level5 == 'Valdemorillo'].mean()
print(f"La media pps para la población de 'Valdemorillo' es de {ppsv:.2f} €/m2")

#Cálculo e Impresión del promedio pps de la población de 'Galapagar'
ppsg = ds1.pps[ds1.level5 == 'Galapagar'].mean()
print(f"La media pps para la población de 'Galapagar' es de {ppsg:.2f} €/m2")

#### Exercise 11. Analyze the relation between the surface and the price of the houses (★★☆)

Hint: You can make a `scatter plot`, then write a conclusion about it.

In [ ]:
# TODO: Code

ds2 = ds1[ds1.surface < 5000]
ds2.plot.scatter(y= 'price', x= 'surface', title = 'Relación entre superficie y Precio de las Casas' )

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 12. How many real estate agencies does the dataset contain? (★★☆)

Print the obtained value.

In [ ]:
# TODO
#Cálculo e Impresion de cantidad total de agencias inmobiliarias en el dataset
inmobiliarias = len(ds1.realEstate_name.unique())
print(f"Hay {inmobiliarias} Agencias de Bienes Raíces en el dataset")

#### Exercise 13. Which is the population (level5 column) that contains the most houses? (★★☆)

Print both the population and the number of houses.

In [ ]:
# TODO
#Cálculo de la población con mayor cantidad de casas
población_mf = ds1['level5'].value_counts().idxmax()

#Cálculo de la cantidad de casas que tiene la población mas frecuente
frecuencia = ds1['level5'].value_counts().max()

#Impresión de información solicitada
print(f"La poblacion de {población_mf} tiene {frecuencia} de casas")

#### Exercise 14. Now let's work with the "south belt" of Madrid. Make a subset of the original DataFrame that contains the following populations (level5 column): "Fuenlabrada", "Leganés", "Getafe", "Alcorcón" (★★☆)

Hint: Filter the original DataFrame using the column `level5` and the function `isin`.

In [ ]:
# TODO
#Asignación de variable para las columnas a filtrar
columnas = ['Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón']

#Nuevo Dataframe Cinturon Sur CS, subconjunto con la información solicitada a partir del Dataframe original ds
CS = ds[ds['level5'].isin(columnas)]

#### Exercise 15. Make a bar plot of the median of the prices and explain what you observe (you must use the subset obtained in Exercise 14) (★★★)

Print the bar of the median of the prices and write in the Markdown cell a brief analysis about the plot.

In [ ]:
# TODO: Code
#Cálculo de la mediana de los precios usando dataset CS
mediana = CS.groupby('level5')['price'].median()

#Codigo para generar un grafico de barras y su impresión
plt.figure(figsize = (8,6))
mediana.plot(kind = 'bar', color = 'skyblue')
plt.title('Mediana de los precios por Población')
plt.xlabel('Poblacion')
plt.ylabel('Mediana del Precio')
plt.xticks(rotation = 45)
plt.tight_layout()

plt.show()

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 16. Calculate the sample mean and variance of the variables: price, rooms, surface area and bathrooms (you must use the subset obtained in Exercise 14) (★★★)

Print both values for each variable.

In [ ]:
#Asignacion de una variable con las columnas de interés
Columnas_interés = ['bathrooms', 'price', 'rooms', 'surface']

#Calculo de la media y varianza para cada una de las columnas seleccionadas
media = CS[Columnas_interés].mean()
varianza = CS[Columnas_interés].var()

#Impresion de los datos solicitados
print('Media de las variables seleccionadas:')
print(media)
print('\nVarianza muestral de las variables seleccionadas')
print(varianza)

#### Exercise 17. What is the most expensive house in each population? You must use the subset obtained in Exercise 14 (★★☆)

Print both the address and the price of the selected house of each population. You can print a DataFrame or a single line for each population.

In [ ]:
#Asignación de variable para las columnas de interés
Columnas_a_usar = ['level5', 'address', 'price']

#Codigo para calcular la casa mas cara de cada población
casas_mas_caras = CS.loc[CS.groupby('level5')['price'].idxmax(), Columnas_a_usar]

#Imprersion de cada casa con dirección y precio
for index, row in casas_mas_caras.iterrows():
    print(f"La casa mas cara de {row['level5']} está en la dirección {row['address']} con un precio de {row['price']}€")

#### Exercise 18. Normalize the variable of prices for each population and plot the 4 histograms in the same plot (you must use the subset obtained in Exercise 14) (★★★)

For the normalization method, you can use the one you consider; there is not a single correct answer to this question. Print the plot and write in the Markdown cell a brief analysis about the plot.

Hint: You can help yourself by reviewing the *multihist* demo of Matplotlib.

In [ ]:
#Importando la biblioteca adicional requerida
from scipy.stats import zscore

#Normalizacion de precios usando zscore
CS = CS.copy()
CS.loc[:, 'precio_normalizado'] = CS.groupby('level5')['price'].transform(zscore)

#Codigo para generar histograma
plt.figure(figsize=(10, 6))

poblaciones = CS['level5'].unique()

for x in poblaciones:
    precios_norm = CS[CS['level5'] == x]['precio_normalizado']
    plt.hist(precios_norm, bins=10, alpha=0.5, label=f'Población: {x}', density=True)

plt.title('Distribución de Precios Normalizados por Población')
plt.xlabel('Precio Normalizado (Z-score)')
plt.ylabel('Densidad')
plt.legend()

plt.tight_layout()
plt.show()

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 19. What can you say about the price per square meter (price/m2) between the towns of "Getafe" and "Alcorcón"? You must use the subset obtained in Exercise 14 (★★☆)

Hint: Create a new column called `pps` (price per square meter) and then analyze the values.

In [ ]:
#Creacion de columna nueva pps para el dataframe CS
CS['pps'] = CS.price / CS.surface

#Calculo e Impresión de media de pps para las poblaciones de interés
ppsGetafe = CS[CS.level5 == 'Getafe'].pps.mean()
ppsAlcorcón = CS[CS.level5 == 'Alcorcón'].pps.mean()

print(f"El precio por metro cuadrado en 'Getafe' es de {ppsGetafe:.2f} €/m2")
print(f"El precio por metro cuadrado en 'Alcorcón' es de {ppsAlcorcón:.2f} €/m2")

#### Exercise 20. Make the same plot for 4 different populations (level5 column) and rearrange them on the same graph. You must use the subset obtained in Exercise 14 (★★☆)
 
Hint: Make a scatter plot of each population using subplots.

In [ ]:
#Codigo para crear la figura y los subplots
fig, axs = plt.subplots(2, 2, figsize=(10, 10))
fig.suptitle('Gráficos de Dispersión por Población', fontsize=16)

poblaciones = CS['level5'].unique()

for i, poblacion in enumerate(poblaciones):
    row = i // 2
    col = i % 2
    
    data = CS[CS['level5'] == poblacion]
    
    #Creación del diagrama de dispersión
    axs[row, col].scatter(data['surface'], data['price'], alpha=0.6)
    
    #Personalización de la figura
    axs[row, col].set_title(f'Población: {poblacion}')
    axs[row, col].set_xlabel('Superficie (m²)')
    axs[row, col].set_ylabel('Precio (€)')
    axs[row, col].grid(True)

plt.tight_layout()
plt.show()

#### Exercise 21. Make a plot of the coordinates (latitude and longitude columns) of the south belt of Madrid by color of each population (you must use the subset obtained in Exercise 14) (★★★★)

Execute the following cell, and then start coding in the next one. You must implement a simple code that transforms the coordinates columns in a Python dictionary (add more information if needed) and then add it to the map

In [ ]:
from ipyleaflet import Map, basemaps

# Mapa centrado en (60 grados latitud y -2.2 grados longitud)
# Latitud, longitud
map = Map(center = (60, -2.2), zoom = 2, min_zoom = 1, max_zoom = 20, 
    basemap=basemaps.OpenStreetMap.Mapnik)
map

In [3]:
## HERE: plot the coordinates of the estates

## PUT HERE YOUR CODE:
#Importando bibliotecas adicionales
from ipyleaflet import MarkerCluster, CircleMarker, AwesomeIcon, Marker

#Diccionario de las columnas 'latitude' y 'longitude' del dataframe CS
coordenadas = CS.groupby('level5')[['latitude', 'longitude']].apply(lambda x: x.to_dict(orient='records')).to_dict()

#Asignación de colores para cada población
colores = {
    'Getafe': 'red',
    'Alcorcón': 'blue',
    'Leganés': 'green',
    'Fuenlabrada': 'purple'
}

#Centrando mapa a la localidad de Madrid, España
mapa = Map(center=(40.4168, -3.7038), zoom=10)

#Creacion de marcadores para las coordenadas
marcadores = []

for level5, coordenadas in coordenadas.items():
    color = colores.get(level5,'gray')  # Default color si no se encuentra en el diccionario
    for coord in coordenadas:
        marcador = CircleMarker(
            location=(coord['latitude'], coord['longitude']),
            radius=5,
            color=color,
            fill_color=color,
            fill_opacity=0.7
        )
        marcadores.append(marcador)

for marcador in marcadores:
    mapa.add_layer(marcador)

#Ubicacion de poblaciones de interés
legend_locations = {
    'Getafe': (40.3, -3.7),
    'Alcorcón': (40.35, -3.8),
    'Leganés': (40.32, -3.75),
    'Fuenlabrada': (40.28, -3.8)
}

for poblacion, color in colores.items():
    icono = AwesomeIcon(name='circle', marker_color=color, icon_color='white')
    marcador_leyenda = Marker(icon=icono, location=legend_locations[poblacion])
    mapa.add_layer(marcador_leyenda)

mapa

NameError: name 'CS' is not defined